import { CSSProperties } from "react";

export const styles: { [key: string]: CSSProperties } = {
  canvas: {
    width: "100%",
    height: "100vh",
    backgroundColor: "#f5f5f5",
    overflow: "hidden",
    position: "relative",
    touchAction: "none",
  },

  inner: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100000px",
    height: "100000px",
    transformOrigin: "top left",
    transition: "transform 0.1s ease-out",
  },

  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },

  modal: {
    backgroundColor: "#fff",
    borderRadius: "16px",
    padding: "24px",
    maxWidth: "600px",
    width: "90%",
    maxHeight: "80vh",
    overflowY: "auto",
    boxShadow: "0 10px 30px rgba(0, 0, 0, 0.3)",
  },

  characterGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(100px, 1fr))",
    gap: "16px",
    marginTop: "16px",
  },

  characterItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8f8f8",
    borderRadius: "12px",
    padding: "10px",
    cursor: "pointer",
    transition: "all 0.2s ease-in-out",
    border: "1px solid transparent",
  },

  characterAvatar: {
    width: "60px",
    height: "60px",
    borderRadius: "50%",
    objectFit: "cover",
    marginBottom: "8px",
  },

  relationshipButton: {
    padding: "10px 16px",
    backgroundColor: "#f0f0f0",
    border: "1px solid #ccc",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "0.2s",
    textAlign: "center",
  },

  relationshipButtonHover: {
    backgroundColor: "#e0f7fa",
    borderColor: "#00acc1",
  },

  modalBackdrop: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  simsModal: {
    backgroundColor: "#f0f0f0",
    borderRadius: "12px",
    padding: "20px",
    width: "80%",
    maxWidth: "800px",
    maxHeight: "80vh",
    overflowY: "auto",
    boxShadow: "0 10px 25px rgba(0, 0, 0, 0.3)",
    border: "3px solid #ffd700",
  },
  modalHeader: {
    backgroundColor: "#ffd700",
    padding: "10px",
    borderRadius: "8px",
    marginBottom: "20px",
  },
  modalTitle: {
    textAlign: "center",
    color: "#333",
    margin: 0,
    fontSize: "20px",
    fontWeight: "bold",
    textShadow: "1px 1px 1px rgba(255,255,255,0.5)",
  },
  relationshipTypes: {
    display: "flex",
    justifyContent: "center",
    gap: "15px",
    marginBottom: "25px",
    flexWrap: "wrap",
  },
  relationshipButton2: {
    padding: "12px 18px",
    borderRadius: "20px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    border: "2px solid #ccc",
    backgroundColor: "#fff",
    cursor: "pointer",
    transition: "all 0.2s ease",
    fontFamily: '"Roboto", sans-serif',
    fontSize: "14px",
    fontWeight: "bold",
  },
  relationshipButtonActive: {
    borderColor: "#ff6b6b",
    backgroundColor: "#ffecec",
    boxShadow: "0 0 10px rgba(255, 107, 107, 0.5)",
  },
  buttonIcon: {
    fontSize: "18px",
  },
  buttonLabel: {
    whiteSpace: "nowrap",
  },
  simsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(120px, 1fr))",
    gap: "20px",
    padding: "10px",
  },
  simCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "8px",
    cursor: "pointer",
    transition: "transform 0.3s ease",
  },
  avatarFrame: {
    width: "80px",
    height: "80px",
    borderRadius: "50%",
    border: "3px solid #ffd700",
    padding: "3px",
    backgroundColor: "#fff",
    overflow: "hidden",
    boxShadow: "0 4px 8px rgba(0,0,0,0.1)",
  },
  simAvatar: {
    width: "100%",
    height: "100%",
    borderRadius: "50%",
    objectFit: "cover",
  },
  simName: {
    fontSize: "14px",
    textAlign: "center",
    fontWeight: "bold",
    color: "#333",
  },
  modalFooter: {
    display: "flex",
    justifyContent: "center",
    marginTop: "30px",
    gap: "15px",
  },
  primaryButton: {
    padding: "12px 24px",
    backgroundColor: "#ff6b6b",
    color: "white",
    border: "none",
    borderRadius: "20px",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "14px",
    transition: "all 0.2s ease",
    boxShadow: "0 2px 5px rgba(0,0,0,0.2)",
  },
  secondaryButton: {
    padding: "12px 24px",
    backgroundColor: "#e0e0e0",
    color: "#333",
    border: "none",
    borderRadius: "20px",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "14px",
    transition: "all 0.2s ease",
    boxShadow: "0 2px 5px rgba(0,0,0,0.1)",
  },
};
